# Chapter 2: Numerical Computing with NumPy
## By: Parisa Hormozzadeh

Numpy is the fundamental package for scientific computing with Python.

It provides support for:
- Powerful N-dimensional array objects
- Sophisticated functions for fast operations on arrays

---

## 1. Installing and Importing Numpy
If you have Anaconda installed, numpy comes pre-installed.
Otherwise, you can install it using:

```bash
pip install numpy
```

To use numpy in your code, import it as:

---

In [1]:
import numpy as np

## 2. Creating Numpy Arrays
Numpy arrays can be created from Python lists or tuples.

- 1D array (vector)
- 2D array (matrix)
- 3D arrays and higher dimensions

---

In [2]:
# 1D array
arr1d = np.array([220, 230, 210, 225])
print("1D array:", arr1d)

# 2D array
arr2d = np.array([[220, 10], [230, 15], [210, 9]])  # voltage, current pairs
print("\n2D array:\n", arr2d)

# 3D array example
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D array:\n", arr3d)

1D array: [220 230 210 225]

2D array:
 [[220  10]
 [230  15]
 [210   9]]

3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 3. Array Attributes
- `shape`: dimensions of the array
- `size`: total number of elements
- `ndim`: number of dimensions
- `dtype`: data type of elements

---

In [3]:
print("Shape of arr2d:", arr2d.shape)
print("Size of arr2d:", arr2d.size)
print("Number of dimensions (ndim):", arr2d.ndim)
print("Data type (dtype):", arr2d.dtype)

Shape of arr2d: (3, 2)
Size of arr2d: 6
Number of dimensions (ndim): 2
Data type (dtype): int32


## 4. Indexing and Slicing
Like Python lists, numpy arrays can be indexed and sliced.

---

In [4]:
# Access first voltage reading
print("First voltage reading:", arr1d[0])

# Slice first three readings
print("First three readings:", arr1d[0:3])

# Access element at 2nd row, 1st column in 2D array
print("Element [1,0] in arr2d:", arr2d[1,0])

First voltage reading: 220
First three readings: [220 230 210]
Element [1,0] in arr2d: 230


## 5. Basic Arithmetic Operations
- Operations apply element-wise on arrays.
- Supported operators: `+`, `-`, `*`, `/`, `**` (power)

---

In [5]:
arr_voltage = np.array([220, 230, 210])
arr_current = np.array([10, 15, 9])

# Calculate power for each reading (element-wise multiplication)
power = arr_voltage * arr_current
print("Power for each reading:", power)

# Add 5 volts to each voltage reading
new_voltage = arr_voltage + 5
print("Voltage after adding 5:", new_voltage)

Power for each reading: [2200 3450 1890]
Voltage after adding 5: [225 235 215]


## 6. Useful Numpy Functions
- `np.mean()`, `np.sum()`, `np.max()`, `np.min()`
- `np.reshape()` to change array shape
- `np.arange()` to create sequences
- `np.linspace()` to create evenly spaced numbers

---

In [6]:
print("Mean voltage:", np.mean(arr_voltage))
print("Sum of currents:", np.sum(arr_current))

# Reshape 1D array to 3x1
reshaped = arr_voltage.reshape((3,1))
print("Reshaped array:\n", reshaped)

# Generate numbers from 0 to 9
print("arange 0 to 9:", np.arange(10))

# Generate 5 numbers between 0 and 1
print("linspace 0 to 1:", np.linspace(0, 1, 5))

Mean voltage: 220.0
Sum of currents: 34
Reshaped array:
 [[220]
 [230]
 [210]]
arange 0 to 9: [0 1 2 3 4 5 6 7 8 9]
linspace 0 to 1: [0.   0.25 0.5  0.75 1.  ]


## 7. Example: Energy Data Calculations
Suppose we have voltage and current readings and want to calculate power and average power.

---

In [7]:
voltage = np.array([220, 230, 210, 225])
current = np.array([10, 15, 9, 12])

power = voltage * current
print("Power readings:", power)
print("Average power:", np.mean(power))

Power readings: [2200 3450 1890 2700]
Average power: 2560.0


## Summary
- Numpy is a powerful tool to work efficiently with numerical data.
- Arrays are faster and consume less memory than Python lists.
- Mastery of Numpy arrays, operations, and functions is essential for data science and ML.

Next up: we will explore **Pandas**, the go-to library for data analysis and manipulation.